i-VRESSE/haddock3-webapp

- app/models/application.server.test.ts
- app/models/applicaton.server.ts
Refs https://github.com/i-VRESSE/workflow-builder/issues/124
> Enforce postprocess

- app/routes/login.tsx
- app/routes/register.tsx
> Style register similar to login

- Dockerfile
- README.md
- app/models/config.server.ts
- docker-compose.yml
Also set BARTENDER_API_URL using env var
> docker compose

- app/models/user.server.ts
- app/routes/admin/index.tsx
- app/routes/admin/users.tsx
- app/routes/applications/builder.tsx
- app/routes/applications/upload.tsx
- app/routes/profile.tsx
As session already contains roles
Fixes #31
> Do not fetch user from accesstoken to get roles

- app/catalogs/index.server.ts
Fixes https://github.com/i-VRESSE/haddock3-webapp/issues/56
> Use default for run_dir

- README.md
- app/routes/jobs.$id.tools.reclustfcc.$module.tsx
- app/tools/recluster.server.ts
> Re tools testing

- app/bartender-client/bartenderschema.d.ts
- app/components/JobName.tsx
- app/components/JobStatus.tsx
- app/models/job.server.ts
- app/routes/jobs.$id.name.ts
- app/routes/jobs.$id.report.tsx
- app/routes/jobs.$id.tools.reclustfcc.$module.tsx
- app/routes/jobs.$id.tools.reclustrmsd.$module.tsx
- app/routes/jobs.$id.tools.rescore.$module.tsx
- app/routes/profile.tsx
- app/routes/register.tsx
Refs #37
#37 wanted to set name before submitting, but this PR allows editing after submission.
This requires running bartender https://github.com/i-VRESSE/bartender/pull/83
> Edit name of submitted job

- app/catalogs/index.server.ts
- app/entry.server.tsx
- app/models/application.server.test.ts
- app/models/applicaton.server.ts
- app/models/errors.ts
- app/root.tsx
- app/routes/builder.tsx
- app/routes/jobs.$id.edit.tsx
- app/routes/upload.tsx
- package-lock.json
- package.json
Refs #22
Refs #30
See https://remix.run/docs/en/main/guides/errors#root-error-boundary
TODO:
> Improve error handling

- .env.example
- app/entry.server.tsx
- app/root.tsx
- package-lock.json
- package.json
When a back service is down we say the admins will be notified. This PR does notification.
Refs #71
> Try out glitchtip for error tracking

- app/catalogs/index.server.ts
> Hide most global parameters on builder page

- app/builder/ClearButton.tsx
- app/builder/DownloadButton.tsx
- app/builder/Form.client.tsx
- app/builder/Form.css
- app/builder/FormActions.tsx
- app/builder/SubmitButton.tsx
- app/builder/UploadButton.tsx
- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- package-lock.json
- package.json
TODO
* add autosave checkbox to builder page or profile page?
> Use workflow builder with autosave

- app/browse/OutputReport.tsx
- app/routes/jobs.$id.tools.reclustfcc.$module.tsx
- app/routes/jobs.$id.tools.reclustrmsd.$module.tsx
- app/scenarios/FormErrors.tsx
- app/tools/MatrixPlot.client.tsx
- app/tools/recluster.server.ts
- deploy/arq/bartender-config.yaml
- deploy/containerslurm/bartender-config.yaml
- deploy/remoteslurm/bartender-config.yaml
> Plot matrix

- .devcontainer/docker-compose.yml
- .github/workflows/docker-cleanup.yml
- deploy/Dockerfile
- deploy/Dockerfile.bartenderhaddock3
- deploy/Dockerfile.dockerignore
- deploy/arq/docker-compose.yml
- deploy/containerslurm/Dockerfile
- deploy/remoteslurm/docker-compose.yml
> Make bartender image multi stage

- app/builder/Form.client.tsx
- app/builder/indexedDB.ts
- app/builder/useIndexedDb.tsx
- app/builder/useSaveOnLeave.tsx
- app/components/JobName.tsx
- app/components/Navbar.tsx
- app/routes/_index.tsx
The preferred way to submit haddock3 jobs is to use one of the scenarios. The builder is for fine tuning or starting from scratch.
Also fixes #134
> Move scenarios page before build page

- .devcontainer/docker-compose.yml
- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- package-lock.json
- package.json
Lockfile was also audit fixed.
> Use latest workflow builder packages and catalogs

- app/routes/scenarios.protein-dna.tsx
- app/routes/scenarios.protein-glycan.tsx
- app/routes/scenarios.protein-protein.tsx
> For protein docking scenario remove all non coord lines.

- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- app/routes/scenarios.protein-ligand.tsx
- app/scenarios/HeteroMoleculeSubForm.client.tsx
- deploy/Dockerfile.bartenderhaddock3
- deploy/containerslurm/Dockerfile
As https://github.com/haddocking/haddock3/issues/914 has been fixed.
> Allow easy expertise level to run protein ligand scenario

- app/mock_portal.ts
- deploy/arq/README.md
- deploy/portal/README.md
- deploy/portal/docker-compose.yml
- deploy/portal/haddock30.nginx.conf
With nginx as reverse proxy and mocked frontend/backend portal (app/mock_portal.ts).
Test by starting portal docker compose see deploy/portal/README.md
Refs #!44
> Run portal mode with docker compose

- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- app/catalogs/index.server.ts
- app/models/application.server.test.ts
- app/models/applicaton.server.ts
Refs https://github.com/haddocking/haddock3/pull/1035
> Update catalog + use debug = false instead of less_io = true

- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- deploy/Dockerfile.bartenderhaddock3
- deploy/containerslurm/Dockerfile
Follow up on https://github.com/haddocking/haddock3/pull/482
> Add openmm module to catalog and docker image

- CONTRIBUTING.md
- README.md
- app/components/PlotlyPlot.tsx
- app/components/plotly-override.css
- package-lock.json
- package.json
Fixes #101
Fixed in cli with https://github.com/i-VRESSE/haddock3/commit/d24a510d70727488465ce28f01a5bef3a649b92c , fixed in webapp with this PR.
> Make plotly menubar render ok

- app/catalogs/haddock3.easy.json
- app/catalogs/haddock3.expert.json
- app/catalogs/haddock3.guru.json
- deploy/Dockerfile.bartenderhaddock3
Update catalogs by
1. Pull haddock3 changes
2. Workflow builder
3. Run https://github.com/i-VRESSE/workflow-builder/blob/main/packages/haddock3_catalog/generate_haddock3_catalog.py
4. Test builder updated catalogs with `yarn dev`
5. Push changes workflow builder to main branch
3. Fetch updated catalogs with `npm run catalogs`
4. Bump cachebuster for haddock3 in deploy/Dockerfile.bartenderhaddock3
5. Rebuild docker images
6. Test new catalog in webapp using devcontainer or arq deployment
> Add sasascore module

- README.md
- app/routes/help.tsx
- deploy/containerslurm/Dockerfile
- deploy/containerslurm/README.md
- docs/portal.md
- docs/stack.md
> Fix deploy/containerslurm/Dockerfile

- deploy/Dockerfile.bartenderhaddock3
- package.json
> Openmm82 numpy2

- deploy/Dockerfile.bartenderhaddock3
- deploy/containerslurm/bartender-config.yaml
Blocked by https://github.com/i-VRESSE/bartender/pull/106
> Make containerslurm deployment enable submitter_as_account

- .github/workflows/docker.yml
- deploy/README.md
> Build haddock3-webapp-portal image
